### ISSUE TITLE
Fileupload with Firefox throws OpenQA.Selenium.WebDriverException with message "zip: not a valid zip file"

### ISSUE THREAD

**Issue by centu81** [aerokube/selenoid#1001]
All is configured as described in the documentation.
For Chrome it works ok. In Zalenium it works ok for both, it just does not work in Selenide with Firefox.

The compose file:
```
version: '3.2'
services:

    selenoid1:
        image: aerokube/selenoid:latest
        volumes:
        - /etc/selenoid:/etc/selenoid
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/Selenoid/logs:/opt/selenoid/logs
        environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=/d/Selenoid/videos/
        command: ["-enable-file-upload", "-conf", "/etc/selenoid/browsers.json", "-log-output-dir","/opt/selenoid/logs", "-limit", "4", "-mem", "2g", "-cpu", "1", "-timeout", "30s", "-session-attempt-timeout", "120s", "-container-network", "selenoid_default"]
        ports:
        - "4444:4444"

    selenoid-ui1:
        image: aerokube/selenoid-ui:latest
        depends_on:
        - selenoid1
        ports:
        - "8080:8080"
        command: ["--selenoid-uri", "http://selenoid1:4444"]
networks:
    default:
        driver: bridge
        attachable: true
```

browsers.json
```
{
        "firefox": {
                "default": "79.0",
                "versions": {
                        "79.0": {
                                "image": "selenoid/vnc_firefox:79.0",

                                "port": "4444",

                                "path": "/wd/hub",

                                "tmpfs": {"/tmp":"size=512m"}
                        }
                }
        },
        "chrome": {
                "default": "84.0",
                "versions": {
                        "84.0": {
                                "image": "selenoid/vnc_chrome:84.0",
                                "port": "4444",
                                "tmpfs": {"/tmp":"size=512m"}
                        }
                }
        }
}
```
