### ISSUE TITLE
Selenoid not recording video on Win10 Pro

### ISSUE THREAD

**Issue by Varro88** [aerokube/selenoid#1017]
Hi! Could you please help - on Windows 10 I'm not able to record/save videos. VNC is enabled, I can see test running in selenoid-ui, but folder video directory is always empty, http://localhost:4444/video/ displays blank page, http://localhost:4444/video/selenoid%sessionId%.mp4 returns 404.
The same project (with appropriate changes to pathes) is working and saving videos on Linux Mint.

I run via `docker-compose up` following yaml:

```
version: '3.4'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    volumes:
      - "/p/QA/SelenoidTest/selenoid:/etc/selenoid"
      - "/p/QA/SelenoidTest/selenoid/video:/opt/selenoid/video"
      - "/p/QA/SelenoidTest/selenoid/logs:/opt/selenoid/logs"
      - "/p/QA/SelenoidTest/selenoid/downloads:/home/selenium/Downloads"
      - "//var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/p/QA/SelenoidTest/selenoid/video/
    command: ["-capture-driver-logs", "-save-all-logs", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-timeout", "10m", "-capture-driver-logs"]
    ports:
      - "4444:4444"
    network_mode: bridge
  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: "selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri","http://selenoid:4444" ]
```

And here's full log:

```
P:\QA\SelenoidTest> docker-compose up
Starting selenoid ... done
Starting selenoid-ui ... done
Attaching to selenoid, selenoid-ui
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Loading configuration files...]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Saving all logs]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Your Docker API version is 1.40]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Timezone: UTC]
selenoid       | 2020/11/06 08:21:11 [-] [INIT] [Listening on :4444]
selenoid-ui    | 2020/11/06 08:21:11 [INIT] [Listening on :8080]
selenoid       | 2020/11/06 08:21:22 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
selenoid       | 2020/11/06 08:21:22 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
selenoid       | 2020/11/06 08:21:22 [0] [LOCATING_SERVICE] [chrome] [86.0]
selenoid       | 2020/11/06 08:21:22 [0] [USING_DOCKER] [chrome] [86.0]
selenoid       | 2020/11/06 08:21:22 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid       | 2020/11/06 08:21:22 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:22 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [0.21s]
selenoid       | 2020/11/06 08:21:22 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
selenoid       | 2020/11/06 08:21:22 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:22 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8] [0.24s]
selenoid       | 2020/11/06 08:21:22 [0] [SERVICE_STARTED] [selenoid/vnc:chrome_86.0] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [0.10s]
selenoid       | 2020/11/06 08:21:22 [0] [PROXY_TO] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41] [http://172.17.0.4:4444]
selenoid       | 2020/11/06 08:21:22 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444] [1]
selenoid       | 2020/11/06 08:21:22 [0] [SESSION_CREATED] [cd71e146d3b3ef376bb3f1403647ec9f] [1] [0.84s]
selenoid       | 2020/11/06 08:21:33 [30] [SESSION_DELETED] [cd71e146d3b3ef376bb3f1403647ec9f]
selenoid       | 2020/11/06 08:21:33 [0] [STOPPING_VIDEO_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:34 [0] [REMOVING_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8]
selenoid       | 2020/11/06 08:21:34 [0] [FAILED_TO_REMOVE_CONTAINER] [5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8] [Error response from daemon: removal of container 5cfa721a87614988efb933adf64f231626e95224c7842f1bc18b8b44dae4ccd8 is already in progress]
selenoid       | 2020/11/06 08:21:34 [0] [REMOVING_CONTAINER] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:34 [0] [CONTAINER_REMOVED] [2ae25f0b731510cbbe78468c855624a0d1f104ee521c0a256d5166957478de41]
selenoid       | 2020/11/06 08:21:34 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid7b08eee3d902d5a9ee0f1360b49bb510.mp4 to /opt/selenoid/video/cd71e146d3b3ef376bb3f1403647ec9f.mp4: rename /opt/selenoid/video/selenoid7b08eee3d902d5a9ee0f1360b49bb510.mp4 /opt/selenoid/video/cd71e146d3b3ef376bb3f1403647ec9f.mp4: no such file or directory]
```
