### ISSUE TITLE
Selenoid Android: can't start session - wait: http://172.17.0.4:4444/wd/hub does not respond in 30s

### ISSUE THREAD

**Issue by TimurNurlygayanov** [aerokube/selenoid#1054]
Hi, I'm trying to start Android emulator in docker and my setup is the following:

Base OS: MacOS Catalina 10.15.7
Docker version 20.10.2, build 2291f61

browser.json:
```
{
  "android": {
    "default": "10.0",
    "versions": {
      "10.0": {
        "image": "selenoid/android:10.0",
        "port": "4444",
        "path": "/wd/hub",
        "selenoid:options": {
          "enableVNC": true,
          "enableVideo": true
        }
      }
    }
  }
}

```

docker-compose.yml:
```
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

When I open http://localhost:8080/#/capabilities/ and click "Create Session" the request fails with the error:
POST http://localhost:8080/wd/hub/session
status code 500  Internal Server Error
Response Body:
`{"status":13,"value":{"message":"wait: http://172.17.0.4:4444/wd/hub does not respond in 30s"}}`

More info:
```bash
docker ps -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                    PORTS                    NAMES
a823c23ffd9d   aerokube/selenoid-ui   "/selenoid-ui --sele…"   34 minutes ago   Up 34 minutes (healthy)   0.0.0.0:8080->8080/tcp   selenoid-android_selenoid-ui_1
9a0f732951c1   aerokube/selenoid      "/usr/bin/selenoid -…"   34 minutes ago   Up 34 minutes             0.0.0.0:4444->4444/tcp   selenoid-android_selenoid_1
```
```bash
 docker image list -a
REPOSITORY             TAG              IMAGE ID       CREATED         SIZE
aerokube/selenoid      latest           c0ab90eb2ac0   2 weeks ago     16.8MB
aerokube/selenoid      latest-release   c0ab90eb2ac0   2 weeks ago     16.8MB
aerokube/selenoid-ui   latest           800e1f3d15fa   4 weeks ago     17.5MB
selenoid/android       10.0             78cbc1c22916   4 months ago    9.33GB
selenoid/android       7.0              0acd62321707   4 months ago    7.09GB
```
