### ISSUE TITLE
Can't start session with android emulator TSC frequency mismatch between VM 

### ISSUE THREAD

**Issue by TimurNurlygayanov** [aerokube/selenoid#1055]
Setup:
Ubuntu Linux 20.04
CPU Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
```
uname -a
Linux xwzard 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@xwzard:/tmp/mozilla_xwizard0# kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

I can successfully start android container and it works, I can connect to the container via VNC and etc.

The command to start the container:
`  docker run -d --name emulator-test -e ENABLE_VNC=true -e SKIN=WXGA800 --privileged -p 5900:5900 -p 8888:4445 selenoid/android:10.0`

But when I'm starting the session with SelenoidUI the docker container with android emulator crashing with the following errors in logs:
```
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 99

PORT=5900
emulator: WARNING: System image is writable
host doesn't support requested feature: CPUID.80000001H:ECX.abm [bit 5]
host doesn't support requested feature: CPUID.80000001H:ECX.abm [bit 5]
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
WARNING. Using fallback path for the emulator registration directory.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

qemu-system-x86_64: warning: TSC frequency mismatch between VM (1995379 kHz) and host (3292519 kHz), and TSC scaling unavailable
qemu-system-x86_64: warning: TSC frequency mismatch between VM (1995379 kHz) and host (3292519 kHz), and TSC scaling unavailable
adb: device offline

```

browsers.json file
```
{
  "android": {
    "default": "7.0",
    "versions": {
      "7.0": {
        "image": "selenoid/android:7.0",
        "port": "4444",
        "path": "/wd/hub",
        "selenoid:options": {
          "enableVNC": true,
          "enableVideo": true,
          "enableLog": true,
          "skin": "WXGA720",
          "env": ["ANDROID_EMULATOR_USE_SYSTEM_LIBS=1"]
        }
      }
    }
  }
}
```

docker-compose.yml
```
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
      - ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
    command: ["-conf", "/etc/selenoid/browsers.json", "-session-attempt-timeout", "2m", "-service-startup-timeout", "2m", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

```

Is there a mistake in configuration? Is there any workaround I can use to start android containers with selenoid?
