### ISSUE TITLE
Video files are created by root user

### ISSUE THREAD

**Issue by sandorzelei** [aerokube/selenoid#1064]
Hi, 

I added the video recorder to my docker setup on jenkins, it works, but all files are created by root user. My jenkins jobs are running with a 'jenkins' user. Unfortunately jenkins user is not able to remove these video files after they were archived.

I tried to define the user for the video recorder and selenoid:latest-release as well, but no luck.

```
  videorecorder:
    image: selenoid/video-recorder:latest-release
    user: "1002:1002"
```

How can I change the owner of the video files?

**Comment by vania-pooh** [comment]
@sandorzelei I don't think it is possible now. However you can use `/video/` API to download the files.

**Comment by sandorzelei** [comment]
@vania-pooh thanks for the quick response. I changed my code to download the videos from the API, I also added the volume to the selenoid configuration. 

My plan is to let selenoid container keep video files inside the container, because if I use any volume jenkins would not be able to remove these files.

```
version: '3'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "${SELENOID_CONFIG}:/etc/selenoid"
      - "videos:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "${SELENOID_LIMIT:-1}", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
    ports:
      - "4444:4444"
    
volumes:
  videos:
```

I have this error:
```
[VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid1f30675253d63cd51461ad06ce4d1634.mp4 to /opt/selenoid/video/d2766b3dac475c05f11dbcc878a30b00.mp4: rename /opt/selenoid/video/selenoid1f30675253d63cd51461ad06ce4d1634.mp4 /opt/selenoid/video/d2766b3dac475c05f11dbcc878a30b00.mp4: no such file or directory]
```

Any idea what should I change in my configuration?
