### ISSUE TITLE
Always_open_pdf_externally and -start-maximized not working

### ISSUE THREAD

**Issue by mhbm** [aerokube/selenoid#1132]
I uses this

```php
 $args = array(
                "--no-proxy-server",
                "--no-default-browser-check",
                "--no-first-run",
                "--disable-boot-animation",
                "--disable-default-apps",
                "--disable-translate",
                "--disable-web-security",
                "--allow-running-insecure-content",
                "--ignore-ssl-errors=yes",
                "--ignore-certificate-errors",
                "--start-maximized",
                "--disable-blink-features=AutomationControlled"
            );

            $chromeOptions->addArguments($args);


 $prefs = array(
                "plugins.plugins_list" => ["enabled" => false, "name" => "Chrome PDF Viewer"],
                "plugins.always_open_pdf_externally" => true,
                "download.default_directory" => $this->selenoid_download_folder,
                "profile.content_settings.exceptions.automatic_downloads.*.setting" => 1,
                "profile.default_content_settings.popups" => 0,
                "profile.default_content_setting_values.geolocation" => 2,
                "profile.password_manager_enabled" => false,
                "download.prompt_for_download" => false,
                "download.directory_upgrade" => true,
                "safebrowsing.enabled" => false,
                "credentials_enable_service" => false,
            );

$chromeOptions->setExperimentalOption(
                'prefs', 
                $prefs
            );

$capabilities = DesiredCapabilities::chrome();
            $capabilities->setCapability(ChromeOptions::CAPABILITY_W3C, $chromeOptions);
            $capabilities->setCapability("enableVNC", true);

            $this->driver = RemoteWebDriver::create($host, $capabilities, 0, 0);

            $this->driver->get($url);


```

This happens in the selenoid-ui

![image](https://user-images.githubusercontent.com/4275903/129432684-ac1400ab-0b72-4b14-a7d1-7068064b1d12.png)

The browser didn't maximized the page, but I put in the args.
This is the first problem.

The second problem is this:

![image](https://user-images.githubusercontent.com/4275903/129432706-004994f4-7ac9-4c18-9679-5278cdda67ed.png)

The pdf file opened in PDF Viewer, but in the configuration of selenium is to open externally.

The Selenoid version is:

You are using Selenoid 1.10.4!

I used the documentation, but all changes that I made didn't fix theses bugs.

**Comment by vania-pooh** [comment]
@mhbm I would check Chromedriver logs in respective log file being saved by Selenoid when `enableLogs` capability is set. Probably Chromedriver is implicitly passing more arguments which prevent Chrome from using your feature. Also in our browser images there is no external PDF viewer installed.

**Comment by mhbm** [comment]
@vania-pooh Thank you for answer my question.
The second problem ( about the pdf preview ) is about that the file is not download automatically. I read the documention of selenoid and I used the instructions , but didn’t work . I need that the download happens automatically.

About the first problem ( that the window is not maximum size ) I follow the documentation too and didn’t work too .

**Comment by vania-pooh** [comment]
@mhbm Selenium has a dedicated `maximize` call that should work.

**Comment by mhbm** [comment]
@vania-pooh  I will try to use this . 
and about the problem with automatically download ?

**Comment by mhbm** [comment]
@vania-pooh  I used the  enableLogs capability.

And the images is :
![image](https://user-images.githubusercontent.com/4275903/129589053-4eede6f2-3e87-408e-a038-0e8ef80a50ef.png)


I will search about this, but the logs didn't show anything

**Comment by vania-pooh** [comment]
@mhbm you are probably going to another Selenium server, not Selenoid.

**Comment by mhbm** [comment]
@vania-pooh  thanks for the answer.

```
####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '3'
services:

  selenoid:
    container_name: selenoid
    network_mode: bridge
    build: .
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "30", "-timeout", "5m"]
    ports:
      - "4445:4444"

  chrome:
    container_name: chrome
    network_mode: bridge
    image: selenoid/vnc_chrome:86.0
    depends_on:
      - selenoid
    links: 
      - selenoid
    ports:
      - "4446:4444"

  ggr:
    container_name: ggr
    network_mode: bridge
    volumes:
      - "./grid-router/:/etc/grid-router"
    image: aerokube/ggr:latest-release
    depends_on:
      - selenoid
    links: 
      - selenoid
    ports:
      - "4444:4444"

  ggr-ui:
    container_name: ggr-ui
    network_mode: bridge
    volumes:
      - "./grid-router/:/etc/grid-router"
    image: aerokube/ggr-ui:latest-release
    depends_on:
      - selenoid
      - ggr
    links:
      - selenoid
    ports:
      - "8888:8888"

  selenoid-ui:
    container_name: selenoid-ui
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    depends_on:
      - selenoid
      - ggr
      - ggr-ui
    links: 
      - ggr-ui
    command: ["--selenoid-uri", "http://ggr-ui:8888"]
    ports:
      - "8080:8080"
    ```
    
    This is my docker-compose.yml

What is the correct selenoid?
