### ISSUE TITLE
[Can't get status: Get "http://selenoid:4444/status": context deadline exceeded]

### ISSUE THREAD

**Issue by VinothMessi** [aerokube/selenoid#1135]
![image](https://user-images.githubusercontent.com/34208574/130318016-f71314ad-3bdf-4fea-9287-261431367502.png)

It was working perfectly few days back, suddenly started receiving the above error

**Comment by VinothMessi** [comment]
**My docker-compose:**
![image](https://user-images.githubusercontent.com/34208574/130318117-e3a2b987-4131-4f42-8c14-ce9f767426da.png)

**browsers.json:**
![image](https://user-images.githubusercontent.com/34208574/130318148-7008fa48-ffec-4459-ac66-d3122b8c3010.png)

**Comment by vania-pooh** [comment]
@VinothMessi your container name is not `selenoid`, so `--selenoid-uri` should use correct value.

**Comment by VinothMessi** [comment]
**Just took it from Selenoid official website:**

![image](https://user-images.githubusercontent.com/34208574/130495896-9d1f7f39-9a7e-4a0d-b3b5-9f34920e6727.png)

**Comment by VinothMessi** [comment]
**Its shows like this in the UI:**

![image](https://user-images.githubusercontent.com/34208574/130497408-29592017-ab35-42d3-9276-a87a14b4ee9f.png)

**Comment by vania-pooh** [comment]
@VinothMessi your container name is different than `selenoid`. Sometimes just restarting Docker helps.

**Comment by VinothMessi** [comment]
**I even matched the container name, restarted docker... everything i have tried. Just last week it was working **perfectly**** 

![image](https://user-images.githubusercontent.com/34208574/130635172-747666e9-7e75-4169-98c8-7d1823d8587a.png)

**Comment by vania-pooh** [comment]
@VinothMessi please don't use `aerokube/selenoid-ui:latest` image. Replace with `aerokube/selenoid-ui:1.10.3` or `aerokube/selenoid-ui:latest-release` (latest release).

**Comment by VinothMessi** [comment]
I tried it all, the issue remains the same. Am following whatever is given in Selenoid website, but its not working

But am sure it happening only recently, everything was working just days before

**Comment by vania-pooh** [comment]
@VinothMessi could be also caused by Docker update. We previously seen such issues in some Docker releases.

**Comment by VinothMessi** [comment]
AH... just updated my docker recently, so how to overcome it?

**Comment by vania-pooh** [comment]
@VinothMessi either downgrade or wait for the new release. Probably switching to edge Docker version could help.

**Comment by VinothMessi** [comment]
I updated to the new docker release and the same issue is persisting :(

Any way to over come it? tried everything that was mentioned :(

**Comment by aandryashin** [comment]
Docker compose runs containers in custom network, you have to give name
that network and tell selenoid to start browsers in that network by passing
-container-network option.

чт, 2 сент. 2021 г., 14:10 Vinoth M ***@***.***>:

**Comment by VinothMessi** [comment]
Tried that also, created a  network named Selenoid and linked both the Selenoid containers to it

![image](https://user-images.githubusercontent.com/34208574/131965750-be0aac24-89e9-4e8b-95a0-02fe31d927a3.png)

![image](https://user-images.githubusercontent.com/34208574/131965791-fb6aefdc-905b-4a71-aa01-43bd1657a64f.png)

Still no use

**Comment by kim-andrew-v** [comment]
I had different issue with connection between selenoid and selenoid-ui

I found that in my docker desktop settings
checkbox  "Use Docker Compose V2 release candidate" was enabled


![IMAGE 2021-09-03 10:12:55](https://user-images.githubusercontent.com/80952601/131973303-4f14c2a2-966a-45dd-9015-12667fb3d625.jpg)

When i disabled it everything went smooth as before. I hope it'll help.

**Comment by VinothMessi** [comment]
Its already disabled for me :(

Which version of docker you using? am using the latest one : Docker version 20.10.8, build 3967b7d (updated it yesterday)

**Comment by kim-andrew-v** [comment]
➜  ~ docker --version
Docker version 20.10.8, build 3967b7d
➜  ~ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

**Comment by VinothMessi** [comment]
Can you share me your compose file?

this is what am using:
![image](https://user-images.githubusercontent.com/34208574/131981789-c81f50de-f86c-4a43-976e-07ed1792fa8c.png)

**Comment by kim-andrew-v** [comment]
Sure thing
![Screenshot 2021-09-03 at 11 31 14](https://user-images.githubusercontent.com/80952601/131983953-0c071523-6b96-4fa7-9ce3-e9b1eba8bb33.png)

**Comment by VinothMessi** [comment]
Found what was causing the issue, in the command i had **"-video-recorder-image", "selenoid/video-recorder:7.1"**
once i removed it is working file

Sorry, just a question in you compose you have a 

**volumes:
   allure-results:
       local: driver**

you never used it : may i know the purpose? ad how to map the absolute path?

**Comment by jimbalatero** [comment]
> I had different issue with connection between selenoid and selenoid-ui
> 
> I found that in my docker desktop settings
> checkbox "Use Docker Compose V2 release candidate" was enabled
> 
> ![IMAGE 2021-09-03 10:12:55](https://user-images.githubusercontent.com/80952601/131973303-4f14c2a2-966a-45dd-9015-12667fb3d625.jpg)
> 
> When i disabled it everything went smooth as before. I hope it'll help.

This worked for me as well.

**Comment by Amraneze** [comment]
I have the same issue. Here is my docker compose file 

````yml
version: "3"
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    ports:
      - "4444:4444"
    network_mode: bridge
    volumes:
      - "./selenoid:/etc/selenoid"
      - "./selenoid-outputs/output/:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid-outputs/video:/opt/selenoid/video"
      - "./selenoid-outputs/logs:/opt/selenoid/logs"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid-outputs/video"
    command: [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-video-output-dir",
        "/opt/selenoid/video",
        "-log-output-dir",
        "/opt/selenoid/logs",
        "-limit",
        "5",
        "-save-all-logs",
        "-enable-file-upload",
      ]

  selenoid-video-recorder:
    image: selenoid/video-recorder:latest-release

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    network_mode: bridge
    command: ["--selenoid-uri", "http://selenoid:4444"]
````

When I ran the command `docker compose up` I get this error ` [Can't get status: Get "http://selenoid:4444/status"]`

Here are docker & docker compose versions:

![image](https://user-images.githubusercontent.com/28459763/142936256-b3d32893-5aa3-4d60-a165-ba7b49d626d7.png)
![image](https://user-images.githubusercontent.com/28459763/142936278-3dbbc6c2-e6b8-44fc-8a5c-b7ec79e20638.png)

When I run docker compose with a new network it works but chrome can't access to my angular project. I'm getting 

![image](https://user-images.githubusercontent.com/28459763/142936421-17b9b871-2688-45f3-b523-b0df67ad5527.png)
