### ISSUE TITLE
DockerFile using VOLUME 

### ISSUE THREAD

**Issue by mhbm** [aerokube/selenoid#1139]
This is my docker-compose file

```
version: '3'
services:

  selenoid:
    container_name: selenoid
    network_mode: bridge
    build: .
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "30", "-timeout", "15m"]
    ports:
      - "4445:4444"

  chrome:
    container_name: chrome
    network_mode: bridge
    image: selenoid/vnc_chrome:86.0
    depends_on:
      - selenoid
    links: 
      - selenoid
    ports:
      - "4446:4444"

  ggr:
    container_name: ggr
    network_mode: bridge
    volumes:
      - "./grid-router/:/etc/grid-router"
    image: aerokube/ggr:latest-release
    depends_on:
      - selenoid
    links: 
      - selenoid
    ports:
      - "4444:4444"

  ggr-ui:
    container_name: ggr-ui
    network_mode: bridge
    volumes:
      - "./grid-router/:/etc/grid-router"
    image: aerokube/ggr-ui:latest-release
    depends_on:
      - selenoid
      - ggr
    links:
      - selenoid
    ports:
      - "8888:8888"

  selenoid-ui:
    container_name: selenoid-ui
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    depends_on:
      - selenoid
      - ggr
      - ggr-ui
    links: 
      - ggr-ui
    command: ["--selenoid-uri", "http://ggr-ui:8888"]
    ports:
      - "8080:8080"

```

This is my Dockerfile

```
FROM selenoid/vnc_chrome:86.0
FROM aerokube/selenoid:latest-release
```

I need to put VOLUME in DockerFile.

Can somebody help me?

Thanks
