### ISSUE TITLE
page crash

### ISSUE THREAD

**Issue by carl-pki** [aerokube/selenoid#1205]
very many requests on chrome, page crash. 

![image](https://user-images.githubusercontent.com/85552832/162098823-3388a9c2-c80c-411a-aa62-16e22142c5e3.png)

![108b9f10d2b8db954c65e820b23115c](https://user-images.githubusercontent.com/85552832/162098727-e7f667f2-9ad6-4dd7-bde2-879c63f8a2d7.png)
![image](https://user-images.githubusercontent.com/85552832/162098861-c220d593-27e6-454e-be48-80e80fcbfc3d.png)

1、docker-compose.yml
``` yaml

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "/home/ubuntu/compose/selenoid/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/ubuntu/selenoid/video:/opt/selenoid/video/" #
      - "/var/ubuntu/selenoid/logs/:/opt/selenoid/logs/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/jenkins/workspace:/opt/docker/fileDownloadLocation"


    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/var/ubuntu/selenoid/video
 
    command: -limit 20 -service-startup-timeout 2m  -timeout 5m  -session-attempt-timeout 2m -retry-count 3 -enable-file-upload -log-output-dir /opt/selenoid/logs
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  video-recorder:
    image: "selenoid/video-recorder:latest-release"
    network_mode: bridge
    restart: always
  vnc:
    image: "selenoid/vnc:chrome_100.0"
    network_mode: bridge
    restart: always


```

2、browser.json
``` json

{
  "chrome": {
    "default": "98.0",
    "versions": {
      "98.0": {
        "image": "selenoid/vnc:chrome_98.0",
        "port": "4444",
        "path": "/",
        "volumes": ["/var/jenkins/workspace:/opt/docker/fileDownloadLocation"]
      },
      "99.0": {
        "image": "selenoid/vnc:chrome_99.0",
        "port": "4444",
        "path": "/",
        "volumes": ["/var/jenkins/workspace:/opt/docker/fileDownloadLocation"]
      },
      "100.0": {
        "image": "selenoid/vnc:chrome_100.0",
        "port": "4444",
        "path": "/",
        "volumes": ["/var/jenkins/workspace:/opt/docker/fileDownloadLocation"]
      }
    }
  },
  "firefox": {
    "default": "79.0",
    "versions": {
      "79.0": {
        "image": "selenoid/vnc:firefox_79.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  },
  "safari": {
    "default": "14.0",
    "versions": {
      "14.0": {
        "image": "browsers/safari:14.0",
        "port": "4444",
        "path": "/"
      }
    }
  },
  "opera": {
    "default": "70.0",
    "versions": {
      "70.0": {
        "image": "selenoid/vnc:opera_70.0",
        "port": "4444",
        "path": "/"
      }
    }
  }
}

```
