### ISSUE TITLE
I need a docker image of selenoid with tags of S3.

### ISSUE THREAD

**Issue by carl-pki** [aerokube/selenoid#1207]
**I need a docker image of selenoid with tags of S3.**

1、Environment and create image
![image](https://user-images.githubusercontent.com/85552832/163200097-b2c38d8a-0e75-4bfb-8305-aff7325ed2cf.png)

2、create docker-compose

```  yaml

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:s3"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "/home/ubuntu/compose/selenoid/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/ubuntu/selenoid/video:/opt/selenoid/video/" #
      - "/var/ubuntu/selenoid/logs/:/opt/selenoid/logs/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/jenkins/workspace:/opt/docker/fileDownloadLocation"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/var/ubuntu/selenoid/video
    command: -limit 20 -service-startup-timeout 2m  -timeout 5m  -session-attempt-timeout 2m -retry-count 3 -enable-file-upload -log-output-dir /opt/selenoid/logs
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  video-recorder:
    image: "selenoid/video-recorder:latest-release"
    network_mode: bridge
    restart: always
  vnc:
    image: "selenoid/vnc:chrome_98.0"
    network_mode: bridge
    restart: always


```
![image](https://user-images.githubusercontent.com/85552832/163201684-d3ad5cf4-87ab-4e0f-91d2-b0a9ae433cca.png)

3、start container

![image](https://user-images.githubusercontent.com/85552832/163201110-b9a70c94-d60b-4abc-b0fb-e9a9638929ee.png)
