### ISSUE TITLE
Cache selenoid in Github Actions - not working

### ISSUE THREAD

**Issue by dhamo-pk** [aerokube/selenoid#1286]
#### The problem
Cache of selenoid in GitHub Actions is not working.

#### Details
There are no error while caching but the retrieving does not happen and I might be wrong so need some details or reference of how exactly caching should be done for this?

#### Code To Reproduce Issue [ Good To Have ]
Pipeline mentions:

```
steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1
```
Console for set up:

```
Run n-ton4/selenoid-github-action@master
 with:
   version: 1.10.1
   args: -limit 10
   browsers: chrome
   last-versions: 1

█████╗ ███████╗██████╗  ██████╗ ██╗  ██╗██╗   ██╗██████╗ ███████╗     ██████╗███╗   ███╗
██╔══██╗██╔════╝██╔══██╗██╔═══██╗██║ ██╔╝██║   ██║██╔══██╗██╔════╝    ██╔════╝████╗ ████║
███████║█████╗  ██████╔╝██║   ██║█████╔╝ ██║   ██║██████╔╝█████╗      ██║     ██╔████╔██║
██╔══██║██╔══╝  ██╔══██╗██║   ██║██╔═██╗ ██║   ██║██╔══██╗██╔══╝      ██║     ██║╚██╔╝██║
██║  ██║███████╗██║  ██║╚██████╔╝██║  ██╗╚██████╔╝██████╔╝███████╗    ╚██████╗██║ ╚═╝ ██║
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝     ╚═════╝╚═╝     ╚═╝

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed

 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 8960k  100 8960k    0     0  45.1M      0 --:--:-- --:--:-- --:--:-- 45.1M

SUCCESSFULLY DOWNLOADED!

Git Revision: 1.8.[2](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:2)
UTC Build Time: 2022-11-17_10:1[3](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:3):27AM

Now you can run Selenoid with cm:
   ./cm selenoid start --vnc

To get instant help just type:
   ./cm --help

> Using Docker
- Your Docker API version is 1.[4](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:4)1
> Downloading Selenoid...
- Pulling image aerokube/selenoid:1.10.1

   [[5](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:5)31e22[6](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:6)c10ac]: Downloading [>                                                  ]  [7](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:8).559kB/674.3kB

   [531e226c10ac]: Verifying Checksum [>                                                  ]  7.559kB/674.3kB

   [531e226c10ac]: Download complete [>                                                  ]  7.559kB/674.3kB

   [[8](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:9)01bfaa63ef2]: Downloading [>                                                  ]  28.75kB/2.7[9](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:10)9MB

   [2dd412dc46de]: Downloading [>                                                  ]  36.88kB/3.586MB

   [188c0c94c7c5]: Extracting [======================================>            ]   2.13MB/2.797MB

   [cff7fd90b61f]: Extracting [>                                                  ]  65.54kB/5.912MB

   [cff7fd90b61f]: Extracting [=======================>                           ]  2.753MB/5.912MB

   [cff7fd90b61f]: Extracting [==============================================>    ]  5.439MB/5.912MB



   [ad32fd45b5d6]: Extracting [>                                                  ]   98.3kB/7.187MB

   [ad32fd45b5d6]: Extracting [=====================>                             ]  3.146MB/7.187MB


> Configuration saved to /home/runner/.aerokube/selenoid/browsers.json
> Starting Selenoid...
> Successfully started Selenoid

## CHECKING STATUS
> Using Docker
- Your Docker API version is 1.41
- Using Selenoid image: aerokube/selenoid:1.[10](https://github.com/xxx/actions/runs/3622676851/jobs/6107677675#step:2:11).1 (sha256:c0ab90eb2ac08573ab96cb481ea5cab6370e6d770d1d7e44091ff0263670ea84)
- Selenoid configuration directory is /home/runner/.aerokube/selenoid
- Selenoid configuration file is /home/runner/.aerokube/selenoid/browsers.json
- Selenoid container is running: selenoid (634ea81286bd595607b752189263087d5de4fc8b0ca10a69f[11]
```

Pipeline mention for Cache: [Are there any elegant way of doing this?]

```
 - name: Cache the Selenoid packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.aerokube
          key: ${{ runner.os }}-aerokube-${{ hashFiles('**/browsers.json') }}
          restore-keys: ${{ runner.os }}-aerokube  

```

Console for Cache:
![image](https://user-images.githubusercontent.com/44419390/206038096-84aa3937-ad31-4e98-88a8-5e5764316380.png)

Console for retrieval:
![image](https://user-images.githubusercontent.com/44419390/206038130-b63c0c16-cb64-448a-9180-bdb5c9129b75.png)
