### ISSUE TITLE
How to add webdriver logs to log file in selenoid

### ISSUE THREAD

**Issue by oleh-datsiuk** [aerokube/selenoid#1349]
Now I have following config

**docker-compose**

```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.10.10
    volumes:
      - "../config/browsers/:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../config/video/:/opt/selenoid/video"
      - "../config/logs/:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/user/Documents/selenium-startert/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir",
               "/opt/selenoid/logs", "-capture-driver-logs", "-save-all-logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.10"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
```

**browsers.json**
```
{
  "firefox": {
    "default": "113.0",
    "versions": {
      "113.0": {
        "image": "selenoid/vnc_firefox:113.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  },
  "chrome": {
    "default": "113.0",
    "versions": {
      "113.0": {
        "image": "selenoid/vnc_chrome:113.0",
        "port": "4444",
        "path": "/"
      }
    }
  }
}
```

And using Selenium I have implemented WebDriverListener to log all actions, like this

```
@Slf4j
public class LoggingWebDriverEventListener implements WebDriverListener {

    @Override
    public void beforeGet(WebDriver driver, String url) {
        log.info("Try to open URL: " + url);
    }

    @Override
    public void afterGet(WebDriver driver, String url) {
        log.info("URL: " + url + " was successfully opened");
    }

    @Override
    public void beforeFindElement(WebDriver driver, By locator) {
        log.info("Trying to find element by [" + locator + "]");
    }

    @Override
    public void afterFindElement(WebDriver driver, By locator, WebElement result) {
        log.info("Element was successfully found by [" + locator + "]");
    }
}
```

And I use following code to start my browser
```
 @SneakyThrows
    @BeforeMethod(onlyForGroups = {"snapshot"})
    public synchronized void setUpDriverForSnapshot(Method m) {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName("chrome");
        capabilities.setVersion("113.0");

        Map<String, Object> selenoidOptions = new HashMap<>();
        selenoidOptions.put("enableVNC", true);
        selenoidOptions.put("enableVideo", true);
        selenoidOptions.put("videoName", m.getName() + ".mp4");
        selenoidOptions.put("enableLog", true);
        selenoidOptions.put("logName", m.getName() + ".log");
        capabilities.setCapability("selenoid:options", selenoidOptions);

        String hubHost = System.getenv("SELENIUM_HUB_URL");
        if (hubHost == null) {
            hubHost = "localhost";
        }
        URL url = new URL("http://" + hubHost + ":4444/wd/hub");

        WebDriver originalDriver = new RemoteWebDriver(url, capabilities);
        LoggingWebDriverEventListener listener = new LoggingWebDriverEventListener();
        WebDriver decoratedWebDriver = new EventFiringDecorator<>(listener).decorate(originalDriver);

        WebDriverRunner.setThreadLocalDriver(decoratedWebDriver);
        WebDriverRunner.getDriver().manage().window().setSize(new Dimension(1920, 1080));
        WebDriverRunner.getDriver().manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
```

For logging I use
```
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.20.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.20.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.20.0</version>
        </dependency>
```

```
# Name of the configuration
name = Selenium Starter log config

# Root logger level
rootLogger.level = info

# Console appender configuration
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = thread=[%tid] %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# File appender configuration
appender.file.type = File
appender.file.name = fileLogger
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = thread=[%tid] %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
appender.file.fileName = src/test/resources/logs/tests.log

# Root logger referring to console appender
rootLogger.appenderRefs = consoleLogger, fileLogger
rootLogger.appenderRef.consoleLogger.ref = consoleLogger
rootLogger.appenderRef.fileLogger.ref = fileLogger

```

**Finally in my console (as well as in src/test/resources/logs/tests.log file) I see my logs**

```
thread=[1] 2023-05-25 20:02:06 INFO  LoggingWebDriverEventListener:15 - Try to open URL: https://somesite.com
thread=[1] 2023-05-25 20:02:07 INFO  LoggingWebDriverEventListener:20 - URL: https://foxminded.ua was successfully opened
thread=[1] 2023-05-25 20:02:07 INFO  LoggingWebDriverEventListener:35 - Trying to find element by [By.xpath: //a[text()='sometext']]
thread=[1] 2023-05-25 20:02:07 INFO  LoggingWebDriverEventListener:40 - Element was successfully found by [By.xpath: //a[text()='sometext']]
```

**But in logs from selenoid containe ("../config/logs/:/opt/selenoid/logs") I see only this**
```
2023-05-26T06:17:45.834237747Z 2023/05/26 06:17:45 [INIT] [Listening on :7070]
2023-05-26T06:17:45.840602600Z 19
2023-05-26T06:17:45.847055142Z Waiting X server...
2023-05-26T06:17:45.896055017Z Logging to: /dev/null
2023-05-26T06:17:45.951041908Z Waiting X server...
2023-05-26T06:17:46.058074636Z Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 4444
2023-05-26T06:17:46.058115420Z All remote connections are allowed. Use an allowlist instead!
2023-05-26T06:17:46.058119815Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-05-26T06:17:46.059074758Z ChromeDriver was started successfully.
2023-05-26T06:17:46.060485982Z 
2023-05-26T06:17:46.060508753Z  --- x11vnc loop: 1 ---
2023-05-26T06:17:46.060512761Z 
2023-05-26T06:17:46.561780726Z  --- x11vnc loop: waiting for: 184
2023-05-26T06:17:46.561815761Z 
2023-05-26T06:17:46.605324820Z PORT=5900
```

So is there possible to save webdriver logs in files from selenoid container?
