### ISSUE TITLE
selenoid getting exited.

### ISSUE THREAD

**Issue by Faisalsahap** [aerokube/selenoid#1379]
Hi,

@vania-pooh 
I am using Linux 64, i3 configured machine. I pulled the aerokube/selenoid:latest image successfully. But the selenoid container is always in the exited state. When I was checking with selenoid-UI, the connection was not established, it threw version unknown. 

Then I tried with aerokube/selenoid:1.11.0 image, and I am still facing the same issue.

**docker-compose.yml:**
```

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.11.0"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_90.0:
    image: "selenoid/vnc:chrome_90.0"
    container_name: chrome_90.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"   
  chrome_116.0:
    image: "selenoid/vnc:chrome_116.0"
    container_name: chrome_116.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"     
  firefox_83.0:
    image: "selenoid/vnc:firefox_83.0"
    container_name: firefox_83.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"               
networks:
  selenoid:
    external: 
      name: selenoid
```

**FYI:**

![Screenshot from 2023-10-15 07-10-18](https://github.com/aerokube/selenoid/assets/89384915/3f2a9259-4b00-444f-af38-0fc615b0c8b5)

Couldn't even get the network id here. 
![Screenshot from 2023-10-15 07-40-44](https://github.com/aerokube/selenoid/assets/89384915/960c76db-ad3c-4b31-8aba-b08dc62e2de9)

![Screenshot from 2023-10-15 07-40-04](https://github.com/aerokube/selenoid/assets/89384915/f6978e7e-a0be-4c81-8f68-588f7d346f6e)
