### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by jonathan-dacruz** [aerokube/selenoid#1382]
Command ran: 
curl -H'Content-Type: application/json' https://url/wd/hub/session -d'{                                                                   
    "capabilities": {   
        "alwaysMatch": {            
            "browserName": "chrome", 
            "google:chromeOptions": {                                           
              "args": ["--no-sandbox",  "--headless" ] 
            },                        
            "browserVersion": "116.0",
            "moon:options": {                                   
                "name": "Session started using curl command...",
                "sessionTimeout": "1m"
            }
        }
    }                            
I'm getting the following error: 
{"value":{"error":"unknown error","message":"unknown error: Chrome failed to start: crashed.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","stacktrace":"#0 0x5627197dde23 \u003Cunknown>\n#1 0x5627195067a7 \u003Cunknown>\n#2 0x56271953150a \u003Cunknown>\n#3 0x56271952ea25 \u003Cunknown>\n#4 0x56271956ed92 \u003Cunknown>\n#5 0x56271956e3af \u003Cunknown>\n#6 0x562719565de3 \u003Cunknown>\n#7 0x562719539a7b \u003Cunknown>\n#8 0x56271953a81e \u003Cunknown>\n#9 0x56271979f638 \u003Cunknown>\n#10 0x5627197a3507 \u003Cunknown>\n#11 0x5627197adc4c \u003Cunknown>\n#12 0x5627197a4136 \u003Cunknown>\n#13 0x5627197729cf \u003Cunknown>\n#14 0x5627197c7b98 \u003Cunknown>\n#15 0x5627197c7d68 \u003Cunknown>\n#16 0x5627197d6cb3 \u003Cunknown>\n#17 0x7fe0cd400b43 \u003Cunknown>\n"}}%   

This is a new installation on GKE.  I've run this with and without args. I've also tried multiple browser versions. 

Current configuration: 
  ```
  selenium:
      MicrosoftEdge:
        repository: quay.io/browser/microsoft-edge-stable
        default: 109.0.1518.70-3
      chrome:
        repository: quay.io/browser/google-chrome-stable
        default: 109.0.5414.119-3
```
