### ISSUE TITLE
Selenoid does not download docker images

### ISSUE THREAD

**Issue by nuBacuk** [aerokube/selenoid#1403]
Selenoid does not download docker images,  but if you download it on the server, it works.

logs
```
2024/02/08 11:18:42 [93] [CREATING_CONTAINER] [selenoid/chrome:120.0]
2024/02/08 11:18:42 [93] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/chrome:120.0]
2024/02/08 11:21:13 [217] [SERVICE_STARTUP_FAILED] [start video container: create video container: Error response from daemon: No such image: selenoid/video-recorder:latest-release]
```

docker-compose
```
version: '3.8'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    command: -limit 6 -retry-count 1000
    volumes:
      - type: bind
        source: /etc/selenoid/
        target: /etc/selenoid/
      - type: bind
        source: /opt/selenoid/video
        target: /opt/selenoid/video/
      - type: bind
        source: /var/log/selenoid/
        target: /opt/selenoid/logs/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    restart: always
    network_mode: bridge
    ports:
      - "4444:4444"
  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    command: --selenoid-uri=http://selenoid:4444
    volumes:
      - type: bind
        source: /etc/selenoid/
        target: /etc/selenoid/
      - type: bind
        source: /opt/selenoid/video
        target: /opt/selenoid/video/
      - type: bind
        source: /var/log/selenoid/
        target: /opt/selenoid/logs/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    restart: always
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    depends_on:
      - selenoid
```

browser.json
```
{
    "chrome": {
        "default": "121.0",
        "versions": {
             "119.0": {
                "image": "selenoid/chrome:119.0",
                "port": "4444",
                "path": "/",
                "selenoid:options": {
                    "enableVNC": "true",
                    "enableLog": "true",
                    "enableVideo": "true"
                  }
            },
            "120.0": {
                "image": "selenoid/chrome:120.0",
                "port": "4444",
                "path": "/",
                "selenoid:options": {
                    "enableVNC": "true",
                    "enableLog": "true",
                    "enableVideo": "true"
                  }
            },
            "121.0": {
                "image": "selenoid/chrome:121.0",
                "port": "4444",
                "path": "/",
                "selenoid:options": {
                    "enableVNC": "true",
                    "enableLog": "true",
                    "enableVideo": "true"
                  }
            },
            "latest": {
                "image": "selenoid/chrome:latest",
                "port": "4444",
                "path": "/",
                "selenoid:options": {
                    "enableVNC": "true",
                    "enableLog": "true",
                    "enableVideo": "true"
                  }
            }
        }
    }
 }
```
docker pull
```
[11:24]root@selenoid01 /opt/selenoid # docker pull selenoid/chrome:120.0
120.0: Pulling from selenoid/chrome
aece8493d397: Already exists
47a975bbe339: Already exists
18ea14de0de9: Already exists
511d609ef775: Already exists
488b8f960dca: Already exists
1f5d87cf52ab: Already exists
362b076eebe8: Already exists
a8504709d044: Pull complete
c524e4721744: Pull complete
77f030279935: Pull complete
6651f4f416f5: Pull complete
8b239296052e: Pull complete
2853cbc5ac6c: Pull complete
Digest: sha256:a719e7a3dcbf8c4914937adcac5f2a6b3e77eebf3374ed652b73b891fd1ae003
Status: Downloaded newer image for selenoid/chrome:120.0
docker.io/selenoid/chrome:120.0
```

docker info
```
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-171-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 9.715GiB
 Name: selenoid01.infra.umschool.dev
 ID: FINT:CKB5:6QUH:6EGS:WH2F:BCYD:L3IX:DHHW:FSNU:XEL2:D5ET:OIVX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
