### ISSUE TITLE
Orchestrate Multiple Selenoid Hubs

### ISSUE THREAD

**Issue by ryanlevell** [aerokube/selenoid#264]
I want to handle multiple selenoid hubs in a simple way. I am pretty new to both Docker and Kubernetes, but I want to run selenoid as a Kubernetes pod.

Currently, I was able to create the Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: selenoid-pod
  labels:
    app: selenium-grid
spec:
  volumes:
    - name: test-cm-vol
      configMap:
        name: test-cm
    - name: docker-sock-vol
      hostPath:
        path: /var/run/docker.sock
  containers:
  - name: selenoid-hub
    image: aerokube/selenoid:latest
    env:
    - name: DOCKER_API_VERSION
      value: "1.24"
    resources:
      requests:
        cpu: 500m
        memory: 750Mi
    volumeMounts:
      - mountPath: /etc/selenoid/browsers.json
        name: test-cm-vol
        subPath: browsers.json
      - mountPath: /var/run/docker.sock
        name: docker-sock-vol
```

However, when I try to run a test I get:
> Exception in thread "main" org.openqa.selenium.WebDriverException: create container: Error: No such image: selenoid/vnc:chrome_62.0 (WARNING: The server did not provide any stacktrace information)

This is because I do not have the [docker images pre-pulled](http://aerokube.com/selenoid/latest/#_image). This is where I am stuck. I am not sure how to pull the (newest) browser images from Kubernetes. This would also require an update to `browsers.json` right? Which is kind of the purpose to `cm` to handle these parts.

Or, is there some other way to handle multiple selenoid hubs simply?
Or to prevent this, is there some flag I can use to force download of the browser images if they are missing?
