### ISSUE TITLE
How to make selenoid container create browser containers using the same network_mode?

### ISSUE THREAD

**Issue by SergioBertolinSG** [aerokube/selenoid#435]
Hi, I'm not sure if this is a bug, so I just ask.

I have connected selenoid container to a vpn using network_mode: "service:vpn", but the containers created for the browsers are not being connected to the vpn. 

This is my docker-compose file:

```
version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - "Europe/Madrid"
    networks:
      - default
    ports:
      - "4444:4444"

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    depends_on:
      - vpn
    environment:
      TZ: 'Europe/Madrid'
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/test/resources/browsersconfig:/etc/selenoid
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "pe-bigdata_default"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    depends_on:
      - selenoid
    environment:
      TZ: 'Europe/Madrid'
    links:
      - vpn:selenoid
    networks:
      - default
    ports:
      - "8082:8080"
    read_only: true
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  default:

```

And the docker version I'm using:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Do you think this is feasible? perhaps it is a bug in selenoid?
