### ISSUE TITLE
unknown command: wd/hub/session

### ISSUE THREAD

**Issue by ivanbogomoloff** [aerokube/selenoid#448]
```bash
./cm selenoid start --vnc --tmpfs 128
> Using Docker
- Your Docker API version is 1.24
registry.ping url=https://registry.hub.docker.com/v2/
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid
```
then
```bash
docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
190dc3339664        aerokube/selenoid:1.6.1   "/usr/bin/selenoid -l"   2 seconds ago       Up 1 seconds        0.0.0.0:4444->4444/tcp   selenoid

docker exec -it selenoid /bin/sh
/ # ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 /usr/bin/selenoid -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -conf /etc/selenoid/browsers.json -video-output-dir /opt/seleno
   13 root       0:00 /bin/sh
   19 root       0:00 ps aux
/ # cat /etc/selenoid/browsers.json
{
    "chrome": {
        "default": "66.0",
        "versions": {
            "65.0": {
                "image": "selenoid/chrome:65.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "66.0": {
                "image": "selenoid/chrome:66.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
```
i got json response "unknown command: wd/hub/session" 
OS ubuntu 14.04
php 5.6
facebook/webdriver 1.1

**Comment by vania-pooh** [comment]
@ivanbogomoloff CM generates `browsers.json` with correct `path` - you incorrectly modified it.

**Comment by vania-pooh** [comment]
@ivanbogomoloff any updates? did it help?

**Comment by vania-pooh** [comment]
Closing because of inactivity. Feel free to reopen if having any more questions.

**Comment by zeburek** [comment]
@vania-pooh 
Also having the same problem:
```yaml
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8086:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

```json
{
  "chrome": {
    "default": "67.0",
    "versions": {
      "67.0": {
        "image": "selenoid/vnc:chrome_67.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  }
}
```

```
>           raise exception_class(value)
E           selenium.common.exceptions.WebDriverException: Message: unknown command: wd/hub/session
```

What is worng with this configs?
