### ISSUE TITLE
Selenoid with docker Swarm - does not respond in 30s

### ISSUE THREAD

**Issue by yosserO** [aerokube/selenoid#564]
This is probably not an issue, but maybe someone can help !!

I'm facing a problem when using selenoid in a docker swarm.
The created browser containers are not accessible and creating a session fails with this error: 

> http://172.x.x.x:4444 does not respond in 30s

As I can see the selenoid container itself joins the overlay network, while the browser containers are connected to the bridge network.

My docker-compose file:

```
version: '3.2'
services:
  selenoid:
    image: "aerokube/selenoid"
    deploy:
      mode: global
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - path/docker:/etc/selenoid
```
    
I tried by specifying 

`command: ["--network", "bridge"]` 

But the created services crush  and try to start again wihtout success.

Thanks for help !!

**Comment by yosserO** [comment]
@vania-pooh am I doing something wrong ?

compose file:
```
version: '3.2'
services:
  selenoid:
    image: "aerokube/selenoid"
    deploy:
      mode: global
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - path/docker:/etc/selenoid
    command: ["--network", "bridge", "-container-network", "bridge"]
```

logs:

> flag provided but not defined: -network

**Comment by yosserO** [comment]
Got it!!

I created an external overlay network and attached the browser containers to it using -container-network

This is what my compose file looks like:

```
version: '3.2'
services:
  selenoid:
    image: "aerokube/selenoid"
    deploy:
      mode: global
    networks:
      - stackdemo_overlay
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - path:/etc/selenoid
    command: ["-container-network", "stackdemo_overlay"]


networks:
  stackdemo_overlay:
     external:
       name: stackdemo_overlay
```
