### ISSUE TITLE
Getting Error - http://172.x.x.x:4444/wd/hub does not respond in 30s

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid#565]
This is my docker-compose running on swarm  and I am using overlay network (as passed in the command for selenoid) .Could anyone please have a look at the compose file and guide if any thing is missing - 

```
version: '2'
services:
  selenoid:
    image: aerokube/selenoid:latest-release

    volumes:
      - "selenoid-config-volume:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "selenoid-data-volume:/opt/selenoid/data"
    environment:
      - constraint:node-type==app-node
    command: ["-conf", "/etc/selenoid/browsers.json","-video-output-dir", "/opt/selenoid/data/video","-timeout","3m","sessionTimeout","2m", "-container-network", "orgselenoiddit_default"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    labels:
      - interlock.hostname=selenoid.org
      - interlock.domain=dit.paascloud.org.com
      - interlock.port=8080

    ports:
        - "8080"
    environment:
        - DBUS_SESSION_BUS_ADDRESS=/dev/null
        - constraint:node-type==app-node
    command: ["--selenoid-uri", "http://ggr-ui:8888"]      

  ggr:
    image: "aerokube/ggr:latest-release"
    environment:
      - constraint:node-type==app-node
    labels:
      - interlock.hostname=ggr.org
      - interlock.domain=dit.paascloud.org.com
      - interlock.port=4444
 
    ports:
        - "4444"
    volumes:
      - "gridrouter-volume:/etc/grid-router"

  ggr-ui:
    image: "aerokube/ggr-ui:latest-release"
    environment:
      - constraint:node-type==app-node
 
    ports:
      - "8888"
    volumes:
      - "gridrouter-volume:/etc/grid-router"
```
