### ISSUE TITLE
[SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444 does not respond in 30s]

### ISSUE THREAD

**Issue by ios116** [aerokube/selenoid#603]
I have **docker-compose file**:

```
version: '3'

services:
  tdd.ru:
    image: tdddjango:2.0
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - ./superlists:/code
    ports:
      - "8003:8000"

  selenoid:
    image: aerokube/selenoid
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

```

**test file:**

```
from selenium import webdriver

capabilities = {
    "browserName": "chrome",
    "version": "69.0",
    "enableVNC": True,
    "enableVideo": False
}

driver = webdriver.Remote(
    command_executor="http://selenoid:4444/wd/hub/",
    desired_capabilities=capabilities)

browser = webdriver.Chrome()
browser.get('http://tdd.ru:8000')
assert 'Django' in browser.title
```

**But I get an error:**

```
selenoid_1     | 2018/11/08 12:04:13 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_69.0]
selenoid_1     | 2018/11/08 12:04:13 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_69.0] [9e455c11bf70e1bbdb492f2f61f5b462d99a6166b66ed65dd39095871348ec16]
selenoid_1     | 2018/11/08 12:04:13 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_69.0] [9e455c11bf70e1bbdb492f2f61f5b462d99a6166b66ed65dd39095871348ec16] [0.31s]
selenoid_1     | 2018/11/08 12:04:43 [0] [REMOVING_CONTAINER] [9e455c11bf70e1bbdb492f2f61f5b462d99a6166b66ed65dd39095871348ec16]
selenoid_1     | 2018/11/08 12:04:44 [0] [CONTAINER_REMOVED] [9e455c11bf70e1bbdb492f2f61f5b462d99a6166b66ed65dd39095871348ec16]
selenoid_1     | 2018/11/08 12:04:44 [0] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444 does not respond in 30s]
```

How i can fix it?
