### ISSUE TITLE
[SERVICE_STARTUP_FAILED] [create container: Error response from daemon: invalid reference format]

### ISSUE THREAD

**Issue by pavelsr** [aerokube/selenoid#789]
When I tried to run simple Perl script ( just get title from google.com) I got following error:

```
selenoid_1     | 2019/08/21 08:25:37 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
selenoid_1     | 2019/08/21 08:25:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
selenoid_1     | 2019/08/21 08:25:37 [8] [LOCATING_SERVICE] [firefox] []
selenoid_1     | 2019/08/21 08:25:37 [-] [DEFAULT_VERSION] [Using default version: 63.0]
selenoid_1     | 2019/08/21 08:25:37 [8] [USING_DOCKER] [firefox] [63.0]
selenoid_1     | 2019/08/21 08:25:37 [8] [CREATING_CONTAINER] [selenoid/vnc:firefox:63.0]
selenoid_1     | 2019/08/21 08:25:37 [8] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: invalid reference format]
```

Selenoid docker-compose:

```
version: '3'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid:/opt/selenoid/video"
      - "$PWD/selenoid:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
        - 8080:8080
    command: --selenoid-uri http://selenoid:4444
```

browsers.json :

```
{
    "firefox": {
        "default": "63.0",
        "versions": {
            "63.0": {
                "image": "selenoid/vnc:firefox:63.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
```

Perl script:

```
use Selenium::Remote::Driver;
my $driver = Selenium::Remote::Driver->new;
$driver->get('http://www.google.com');
print $driver->get_title();
$driver->quit();
```

What could be the problem?
Is it possible to debug incoming JSON with `/usr/bin/selenoid` options ?
