### ISSUE TITLE
Support macvlan network

### ISSUE THREAD

**Issue by giggio** [aerokube/selenoid#795]
I am using a macvlan network on Docker, and I'm getting an error message:

````
[SERVICE_STARTUP_FAILED] [no bindings available for 4444/tcp]
````

On a Macvlan network all ports are exposed, but it seems that Selenoid is not able to understand that somehow.

This is the line that seems to be doing it:

https://github.com/aerokube/selenoid/blob/db901aa6cf9a67912a9df777a4c1ddf81ca3019f/service/docker.go#L187

**Comment by vania-pooh** [comment]
@giggio we have never used macvlan mode with Docker, so yes - currently Selenoid does not support macvlan I think.

**Comment by giggio** [comment]
I was able to get it to work with a workaround. I added solenoid to both networks. This is my docker-compose.yaml (`lan_net` is a macvlan network, `solenoidnet` is a regular bridge network):

````yaml
version: '3.7'
services:
  selenoid:
    build:
      context: .
      dockerfile: Dockerfile.selenoid
    image: lambda3/selenoid
    container_name: selenoid
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    restart: always
    command: [ "-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/", "-container-network", "selenoidnet" ]
    ports:
     - "4444:4444" # unnecessary, but needed because of selenoid
    networks:
      lan_net:
        ipv4_address: 10.237.107.246
      selenoidnet: {}
  selenoidui:
    build:
      context: .
      dockerfile: Dockerfile.selenoidui
    image: lambda3/selenoidui
    container_name: selenoidui
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    depends_on:
      - selenoid
    command: --selenoid-uri=http://selenoid:4444 --listen :80
    networks:
      lan_net:
        ipv4_address: 10.237.107.245
      selenoidnet: {}
networks:
  lan_net:
    external:
      name: lan_net
  selenoidnet:
    external:
      name: selenoidnet
````

This works, and maybe there is nothing else you need to do, just maybe document it. The containers get created on a bridge network, which is fine, as we only need access to Solenoid and the UI, not the browser containers. I still need to test VNC etc, but this seems fine.

**Comment by vania-pooh** [comment]
@giggio ok, will document it. Thank you for clarification!

**Comment by giggio** [comment]
Ok, I evolved it to a simpler design, adding a reverse nginx proxy. It could be a good alternative to the one I posted above. I leave all the selenoid machinery on one network, not a macvlan, and then I add an nginx proxy to both the selenoid network and the macvlan network. It worked perfectly.

````yaml
version: '3.7'
services:
  selenoid:
    build:
      context: .
      dockerfile: Dockerfile.selenoid
    image: lambda3/selenoid
    container_name: selenoid
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    restart: always
    command: [ "-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/", "-container-network", "selenoidnet" ]
    networks:
      selenoidnet: null
  selenoidui:
    build:
      context: .
      dockerfile: Dockerfile.selenoidui
    image: lambda3/selenoidui
    container_name: selenoidui
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    depends_on:
      - selenoid
    command: --selenoid-uri=http://selenoid:4444 --listen :80 -allowed-origin *
    networks:
      lan_net:
        ipv4_address: 10.237.107.245
      selenoidnet: null
  selenoidproxy:
    image: nginx:1.17-alpine
    container_name: selenoidproxy
    networks:
      lan_net:
        ipv4_address: 10.237.107.246
      selenoidnet: null
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/lambda3.com.br.crt:/etc/ssl/lambda3.com.br.crt
      - ./certs/lambda3.com.br.key:/etc/ssl/lambda3.com.br.key
    restart: always
networks:
  lan_net:
    external:
      name: lan_net
  selenoidnet:
    external:
      name: selenoidnet
````
