### ISSUE TITLE
Chrome Browser fails to start in the container

### ISSUE THREAD

**Issue by deepticake** [aerokube/selenoid#801]
Details:
1. The browser comes up for a flash of a second and shuts down causing the next test step which is to set the cookie to fail.
Error: 
```
UnableToSetCookieError: unable to set cookie
  (Session info: chrome=77.0.3865.75)
    at Object.throwDecodedError (/usr/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/app/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/usr/app/node_modules/selenium-webdriver/lib/http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async thenableWebDriverProxy.execute (/usr/app/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
    at async loginWithRoles (/usr/app/features/support/pages/common.js:16:3)
```

The code which sets the cookie is: 
```
await driver.get(TARGET_HOST)
  await driver.manage().addCookie({
    name: 'token',
    value: tokenValue,
    httpOnly: true,
    domain: TARGET_HOST_DOMAIN,
    path: '/',
    secure: false
  })
  await driver.get(TARGET_HOST)
  return driver.manage().window().setRect({width: 1920, height: 3000})
```

These tests have been running fine until 13-09-2019. This coincides with the date when `selenoid/chrome:latest` was updated.

I am using the below docker images in the compose file:
aerokube/selenoid:latest-release
selenoid/video-recorder:latest-release
selenoid/chrome:latest
 
Selenium-webdriver: 4.0.0-alpha.4

The docker images are pulled fresh before running the test. 

Any tips to debug would be helpful

**Comment by vania-pooh** [comment]
@deepticake using `selenoid/chrome:latest` is a bad idea - to have a stable cluster use tagged images, e.g. `selenoid/chrome:76.0`.

**Comment by deepticake** [comment]
@vania-pooh That did not help. Now I see the below error: 
```
 WebDriverError: create container: Error response from daemon: No such image: selenoid/chrome:latest
           at Object.checkLegacyResponse (/usr/app/node_modules/selenium-webdriver/lib/error.js:585:15)
           at parseHttpResponse (/usr/app/node_modules/selenium-webdriver/lib/http.js:551:13)
           at Executor.execute (/usr/app/node_modules/selenium-webdriver/lib/http.js:486:26)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by vania-pooh** [comment]
@deepticake you have to restart Selenoid after changing config file.

**Comment by deepticake** [comment]
I use docker-compose to pull all the images. All the previous images are deleted before pulling new images. 

The docker-compose file is:
```
version: "2.1"
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    command: -listen :4444 -conf /etc/selenoid/browsers.json -limit 4 -video-output-dir /opt/selenoid/video -log-output-dir /opt/selenoid/logs -timeout 3m -container-network ${NETWORK_TAG}
    ports:
      - 4444:4444
    volumes:
      - "$PWD:/etc/selenoid/:ro" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/test/cucumber-ui-tests/report/screenshots/video:/opt/selenoid/video/"
      - "$PWD/test/cucumber-ui-tests/report/screenshots/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/test/cucumber-ui-tests/report/screenshots/video/
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://selenoid:4444/status"]
      interval: 60s
      timeout: 20s
      retries: 5
    links:
      - web-server
    networks:
      - webui
  
  seleniod-video-recorder:
    image: selenoid/video-recorder:latest-release
    environment:
      - HUB_HOST=selenoid
      - HUB_PORT=4444
    networks:
      - webui  
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://selenoid:4444/status"]
      interval: 60s
      timeout: 20s
      retries: 5    
      
  selenoid-chrome:
    image: selenoid/chrome:77.0
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    depends_on:
      - selenoid
    environment:
      - HUB_HOST=selenoid
      - HUB_PORT=4444
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://selenoid:4444/status"]
      interval: 60s
      timeout: 20s
      retries: 5
    links:
      - web-server
    networks:
      - webui

  testrunner:
    build:
      context: ./test/cucumber-ui-tests
      dockerfile: selenium-tests.dockerfile
    environment:
      - TESTRUNNER_TARGET_HOST=http://web-server:3000
      - TESTRUNNER_TARGET_HOST_DOMAIN=web-server
      - SELENIUM_REMOTE_URL=http://selenoid:4444/wd/hub
      - CI=true
      - WEBUI_JWT_SIGNING_SECRET=fooBarBazBamTech
      - CUCUMBER_PARALLEL=true
    links:
      - selenoid
      - selenoid-chrome
      - web-server
    depends_on:
      selenoid:
        condition: service_healthy
    volumes:
      - ./package.json:/usr/app/app-package.json
      - ./browsers.json:/usr/app/browsers.json
      - ./test/cucumber-ui-tests/package.json:/usr/app/package.json
      - ./test/cucumber-ui-tests/package-lock.json:/usr/app/package-lock.json
      - ./test/cucumber-ui-tests/features:/usr/app/features
      - ./test/cucumber-ui-tests/report:/usr/app/report
      - ./test/cucumber-ui-tests/generate-report.js:/usr/app/generate-report.js
      - ./test/cucumber-ui-tests/report/screenshots/video:/opt/selenoid/video
      - ./test/cucumber-ui-tests/report/screenshots/logs:/opt/selenoid/logs
    networks:
      - webui
    command: npm run test
networks:
  webui:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1200
```

The `browser.json` has: 
```
{
    "chrome": {
      "default": "77.0",
      "versions": {
        "77.0": {
          "image": "selenoid/chrome",
          "port": "4444",
          "tmpfs": {
            "/tmp": "size=512m"
          }
        }
      }
    }
  }
```

The docker images are:
```
selenoid/chrome                    77.0
aerokube/selenoid                  latest-release
selenoid/video-recorder            latest-release
```

What can I start probing to debug the issue?

**Comment by vania-pooh** [comment]
@deepticake could be a Chromedriver \ client issue then. Selenoid just proxies everything to Chromedriver.

**Comment by deepticake** [comment]
Did a little more digging and found the below in the logs: 
```
2019-09-19T09:45:45.261739500Z [1568886345.261][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --load-extension=/tmp/.com.google.Chrome.BN61gJ/internal --log-level=0 --no-first-run --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.tgvQi5 data:,
2019-09-19T09:45:46.198999900Z [66:92:0919/094546.198199:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2019-09-19T09:45:46.498482100Z [107:107:0919/094546.498042:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
2019-09-19T09:45:46.643053600Z [66:301:0919/094546.636213:ERROR:bus.cc(394)] Failed to connect to the bus: Address does not contain a colon
2019-09-19T09:45:46.647979900Z 
2019-09-19T09:45:46.648037100Z DevTools listening on ws://127.0.0.1:33983/devtools/browser/30766f63-6ee0-4b36-b345-4882a2968261
2019-09-19T09:45:46.649657500Z [1568886346.649][DEBUG]: DevTools HTTP Request: http://localhost:33983/json/version
2019-09-19T09:45:46.744618600Z 
2019-09-19T09:45:46.744680900Z (google-chrome:66): LIBDBUSMENU-GLIB-WARNING **: 09:45:46.744: Unable to get session bus: Address element ?/dev/null? does not contain a colon (:)
```

The docker compose is configured in the below manner for chrome: 
```
  selenoid-chrome:
    image: selenoid/chrome:77.0
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    depends_on:
      - selenoid
    environment:
      - HUB_HOST=selenoid
      - HUB_PORT=4444
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://selenoid:4444/status"]
      interval: 60s
      timeout: 20s
      retries: 5
    links:
      - web-server
    networks:
      - webui
```

Could you point to me an example of docker-compose file for selenoid-chrome?
