### ISSUE TITLE
IE11 500 Internal Server Error

### ISSUE THREAD

**Issue by davidulbrich** [aerokube/selenoid#820]
I followed the instructions on [this page](https://github.com/aerokube/windows-images) to create windows docker containers with IE11 and Edge.

Then I started selenoid and selenoid-ui with docker-compose.

```
#docker-compose.yml
version: '3'
networks:
  selenoid:
    external:
      name: selenoid
services:
  selenoid:
    networks:
      selenoid: null
    container_name: selenoid
    image: "aerokube/selenoid:latest-release"
    ports:
      - "4444:4444"
    volumes:
      - "/home/dockertest/CBT/selenoid:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
               "-container-network", "selenoid"
             ]

  selenoid-ui:
    networks:
      selenoid: null
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```
```
#browsers.json

{
     "internet explorer": {
        "default": "11",
        "versions": {
            "11": {
                   "image": "windows:10",
                   "port": "4444",
                   "volumes" : ["/windows-images/ie11/data:/data"]
            }
        }
    },
    "MicrosoftEdge": {
        "default": "18",
        "versions": {
            "18": {
                   "image": "windows:10",
                   "port": "4444",
                   "path": "",
                   "volumes" : ["/windows-images/edge18/data:/data"]                                
            }
        }
    }
}
```

```
#entrypoint.sh

#!/bin/bash

SCREEN_RESOLUTION=${SCREEN_RESOLUTION:-"1024x768x24"}
DISPLAY_NUM=99
export DISPLAY=":$DISPLAY_NUM"

clean() {
  if [ -n "$XVFB_PID" ]; then
    kill -TERM "$XVFB_PID"
  fi
  if [ -n "$X11VNC_PID" ]; then
    kill -TERM "$X11VNC_PID"
  fi
}

trap clean INT TERM

xvfb-run -l -n $DISPLAY_NUM -s "-ac -screen 0 $SCREEN_RESOLUTION -noreset -listen tcp" \
  qemu-system-x86_64 -enable-kvm \
    -machine q35 -smp sockets=1,cores=1,threads=2 -m 2048 \
    -usb -device usb-kbd -device usb-tablet -rtc base=localtime \
    -net nic,model=virtio -net user,hostfwd=tcp::4444-:4444 \
    -drive file=/data/snapshot.img,media=disk,if=virtio \
    -loadvm windows &

XVFB_PID=$!

retcode=1
until [ $retcode -eq 0 ]; do
  xdpyinfo -display $DISPLAY >/dev/null 2>&1
  retcode=$?
  if [ $retcode -ne 0 ]; then
    echo Waiting xvfb...
    sleep 1
  fi
done

x11vnc -display $DISPLAY -passwd selenoid -shared -forever -loop500 -rfbport 5900 -rfbportv6 5900 -logfile /dev/null &
X11VNC_PID=$!

wait
```
If I now start an ie11 session in the selenoid-ui, the session fails with error 500 Internal Server Error.

```
selenoid       | 2019/10/22 13:16:38 [-] [NEW_REQUEST] [unknown] [10.48.113.211]
selenoid       | 2019/10/22 13:16:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.48.113.211]
selenoid       | 2019/10/22 13:16:38 [78] [LOCATING_SERVICE] [internet explorer] [11]
selenoid       | 2019/10/22 13:16:38 [78] [USING_DOCKER] [internet explorer] [11]
selenoid       | 2019/10/22 13:16:38 [78] [CREATING_CONTAINER] [windows:10]
selenoid       | 2019/10/22 13:16:40 [78] [STARTING_CONTAINER] [windows:10] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa]
selenoid       | 2019/10/22 13:16:41 [78] [CONTAINER_STARTED] [windows:10] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa] [1.17s]
selenoid       | 2019/10/22 13:17:05 [78] [SERVICE_STARTED] [windows:10] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa] [24.12s]
selenoid       | 2019/10/22 13:17:05 [78] [PROXY_TO] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa] [http://172.30.0.5:4444]
selenoid       | 2019/10/22 13:17:05 [78] [SESSION_ATTEMPTED] [http://172.30.0.5:4444] [1]
selenoid       | 2019/10/22 13:17:05 [78] [SESSION_FAILED] [http://172.30.0.5:4444] [500 Internal Server Error]
selenoid       | 2019/10/22 13:17:05 [78] [REMOVING_CONTAINER] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa]
selenoid       | 2019/10/22 13:17:06 [78] [CONTAINER_REMOVED] [c4701bc065ae08b4c74bd8447e627dcf21f1051f986494030c8c3873e4b9c0aa]
```

When I start an edge session in the selenoid-ui it works as expected. I can access the browser via VNC.

Is there something wrong in my ie11 configuration?
