### ISSUE TITLE
Add instructions how to run in Docker Compose

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#88]
```
version: '2'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
```
