### ISSUE TITLE
"Does not respond in 30s" error during running tests inside the container

### ISSUE THREAD

**Issue by danylokholodov** [aerokube/selenoid#911]
Hi Team,

I have an issue during running UI tests inside the container

> E       selenium.common.exceptions.WebDriverException: Message: wait: http://172.17.0.2:4444 does not respond in 30s

Here is logs from selenoid:

> docker logs selenoid               
> 2020/05/06 19:13:47 [-] [INIT] [Loading configuration files...]
> 2020/05/06 19:13:47 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
> 2020/05/06 19:13:47 [-] [INIT] [Video Dir: /opt/selenoid/video]
> 2020/05/06 19:13:47 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
> 2020/05/06 19:13:47 [-] [INIT] [Your Docker API version is 1.40]
> 2020/05/06 19:13:47 [-] [INIT] [Timezone: UTC]
> 2020/05/06 19:13:47 [-] [INIT] [Listening on :4444]
> 2020/05/06 19:16:37 [-] [NEW_REQUEST] [unknown] [172.28.0.5]
> 2020/05/06 19:16:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.28.0.5]
> 2020/05/06 19:16:37 [0] [LOCATING_SERVICE] [chrome] [latest]
> 2020/05/06 19:16:37 [0] [USING_DOCKER] [chrome] [latest]
> 2020/05/06 19:16:37 [0] [CREATING_CONTAINER] [selenoid/chrome]
> 2020/05/06 19:16:37 [0] [STARTING_CONTAINER] [selenoid/chrome] [56ff690319d4380da7a7d0d65be8ffe79d43c4139d44575b5e34db3f3d864d1d]
> 2020/05/06 19:16:37 [0] [CONTAINER_STARTED] [selenoid/chrome] [56ff690319d4380da7a7d0d65be8ffe79d43c4139d44575b5e34db3f3d864d1d] [0.21s]
> 2020/05/06 19:17:07 [0] [REMOVING_CONTAINER] [56ff690319d4380da7a7d0d65be8ffe79d43c4139d44575b5e34db3f3d864d1d]
> 2020/05/06 19:17:07 [0] [CONTAINER_REMOVED] [56ff690319d4380da7a7d0d65be8ffe79d43c4139d44575b5e34db3f3d864d1d]
> 2020/05/06 19:17:07 [0] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444 does not respond in 30s]

Inside the container where I execute tests I've checked Selenoid status and everything looks ok:

> docker-compose exec product /bin/sh
> /product/src # curl http://selenoid:4444/status
> {"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"latest":{}}}}
> /product/src # curl http://selenoid:4444/wd/hub/status
> {"value":{"message":"Selenoid 1.10.0 built at 2020-01-16_11:29:22AM","ready":true}}
> /product/src # curl -s http://selenoid:4444/ping
> {"uptime":"9m5.820489025s","lastReloadTime":"2020-05-06T19:13:47Z","numRequests":2,"version":"1.10.0"}

Here is my config:
**docker-compose.yml** (also there are some other services related to a testing product)
```
version: '3'
services:
  chrome:
    container_name: chrome
    image: selenoid/chrome:latest
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - "./automation/testing:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./automation/testing/video:/opt/selenoid/video"
      - "./automation/testing/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./automation/testing/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
```

**conftest.py** (here I initialize a browser)
```
    capabilities = {
        "browserName": "chrome",
        "version": "latest",
        "enableVNC": False,
        "enableVideo": False
    }
    browser = webdriver.Remote(command_executor="http://selenoid:4444/wd/hub", desired_capabilities=capabilities)
```

**browsers.json**

```
{
	"chrome": {
		"default": "latest",
		"versions": {
			"latest": {
				"image": "selenoid/chrome",
				"port": "4444",
				"tmpfs": {"/tmp":"size=512m"}
			}
		}
	}
}
```

Could you please help why I have an error with "does not respond in 30s"?

Thanks in advance!
