### ISSUE TITLE
chrome-mobile /wd/hub does not respond

### ISSUE THREAD

**Issue by saurabh2k26** [aerokube/selenoid#935]
I am trying to run testcafe with selenoid. **It works perfectly for chrome images**, but for chrome-mobile i am getting issues.

docker-compose.yml
```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/home/saurabh/test/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/saurabh/test/config/video:/opt/selenoid/video"
      - "/home/saurabh/test/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/saurabh/test/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
```

browsers.json
```
{
    "chrome": {
        "default": "mobile-79.0",
        "versions": {
            "mobile-79.0": {
                "image": "selenoid/chrome-mobile:79.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
```

Running testcafe:
```
$testcafe selenium:chrome my_first_test.js 
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "selenium:chrome" due to error.

WebDriverError: wait: http://172.17.0.3:4444/wd/hub does not respond in 30s
    at Object.checkLegacyResponse (/home/saurabh/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/home/saurabh/node_modules/selenium-webdriver/lib/http.js:556:13)
    at Executor.execute (/home/saurabh/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Docker-compose logs:
```
$ sudo docker-compose up
Pulling selenoid (aerokube/selenoid:latest-release)...
latest-release: Pulling from aerokube/selenoid
Digest: sha256:ed5cd4ba7d8de40a514667684484dfac34e5ad7d38d875f86bde5bda51e675c8
Status: Downloaded newer image for aerokube/selenoid:latest-release
Creating test_selenoid_1 ... done
Attaching to test_selenoid_1
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Loading configuration files...]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Your Docker API version is 1.40]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Timezone: UTC]
selenoid_1  | 2020/06/13 13:21:39 [-] [INIT] [Listening on :4444]
selenoid_1  | 2020/06/13 13:22:34 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
selenoid_1  | 2020/06/13 13:22:34 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
selenoid_1  | 2020/06/13 13:22:34 [0] [LOCATING_SERVICE] [chrome] []
selenoid_1  | 2020/06/13 13:22:34 [-] [DEFAULT_VERSION] [Using default version: mobile-79.0]
selenoid_1  | 2020/06/13 13:22:34 [0] [USING_DOCKER] [chrome] [mobile-79.0]
selenoid_1  | 2020/06/13 13:22:34 [0] [CREATING_CONTAINER] [selenoid/chrome-mobile:79.0]
selenoid_1  | 2020/06/13 13:22:34 [0] [STARTING_CONTAINER] [selenoid/chrome-mobile:79.0] [d8f7372251d3c009f7e77b9eb525451efa8e81385e6add2d779ef5a691227afe]
selenoid_1  | 2020/06/13 13:22:34 [0] [CONTAINER_STARTED] [selenoid/chrome-mobile:79.0] [d8f7372251d3c009f7e77b9eb525451efa8e81385e6add2d779ef5a691227afe] [0.40s]
selenoid_1  | 2020/06/13 13:23:04 [0] [REMOVING_CONTAINER] [d8f7372251d3c009f7e77b9eb525451efa8e81385e6add2d779ef5a691227afe]
selenoid_1  | 2020/06/13 13:23:04 [0] [CONTAINER_REMOVED] [d8f7372251d3c009f7e77b9eb525451efa8e81385e6add2d779ef5a691227afe]
selenoid_1  | 2020/06/13 13:23:04 [0] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.3:4444/wd/hub does not respond in 30s]
```
