### ISSUE TITLE
windows 10 issues with selenoid

### ISSUE THREAD

**Issue by AleksanderPopov** [aerokube/selenoid#95]
Hi guys! I have an issue trying to launch selenoid on win10. Firstly, documentation is written for unix systems, so 

```
docker run -d --name selenoid                     \
    -p 4444:4444                                    \
    -v `pwd`:/etc/selenoid:ro                       \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    aerokube/selenoid
```

won't work cause of docker.sock volume line:

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid bind mount spec "/C/Program Files/Git/var/run/docker.sock;C:\\Program Files\\Git\\var\\run\\docker.sock": invalid volume specification: '/C/Program Files/Git/var/run/docker.sock;C:\Program Files\Git\var\run\docker.sock': invalid mount config for type "bind": invalid mount path: '\Program Files\Git\var\run\docker.sock' mount path must be absolute.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
after some googling i added extra slash  `//var/run/docker.sock` and that kinda worked, but then i tried to run simple tests using selenoid, whey were finished successfully, but i was able to see all the chrome browsers running and doing their stuff.

Also when i was trying to connect selenoid-ui to selenoid, using 

`$ docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui -selenoid-uri http://localhost:4444`

there was an error message:
```
$ docker logs selenoid-ui
2017/05/25 21:37:56 Listening on :8080
2017/05/25 21:38:00 Client added. 1 registered clients
2017/05/25 21:38:00 Client added. 2 registered clients
2017/05/25 21:38:01 can't get status (Get http://localhost:4444/status: dial tcp 127.0.0.1:4444: getsockopt: connection refused)
2017/05/25 21:38:01 Removed client. 1 registered clients
2017/05/25 21:38:06 can't get status (Get http://localhost:4444/status: dial tcp 127.0.0.1:4444: getsockopt: connection refused)
```

My question is - are selenoid should/able work under windows 10 ? And if yes, can you please clarify my mistakes?

**Comment by vania-pooh** [comment]
@AleksanderPopov hi, are you speaking about native Windows Docker version or a version using virtual machine with Linux inside?

**Comment by aandryashin** [comment]
When run within container you should provide host ip address instead of localhost.

**Comment by AleksanderPopov** [comment]
@vania-pooh hi, yes, boot2docker
@aandryashin do you mean '127.0.0.1' instead of 'localhost' ?

**Comment by aandryashin** [comment]
No, I mean docker machine ip.

**Comment by aandryashin** [comment]
With docker machine everything should work. Please see complete documentation at:
http://aerokube.com/selenoid/latest/

**Comment by vania-pooh** [comment]
@AleksanderPopov we mean host machine IP address in bridge network used by Docker. E.g. under Linux this is something like 172.17.x.x. Related SO question: https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container

**Comment by AleksanderPopov** [comment]
@vania-pooh , @aandryashin thank you guys, with your help i figured out to run selenoid and ui on windows 10. Is there possibility to run they both via docker-compose ?
I did YAML like 

```
version: '2'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"

  selenoid-ui:
    network_mode: host
    image: aerokube/selenoid-ui:1.0.0
    ports:
      - "8080:8080"
```
and it works for unix, but if i should use for windows -selenoid-url option this won't work... Can you please clarify, is there possibility to run selenoid+selenoid-ui at windows via docker-compose?

**Comment by vania-pooh** [comment]
@AleksanderPopov I think host network_mode will not work on Windows (at least does not work with the same VirtualBox architecture on Mac). I think you need something like:
```
selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:1.0.0
    ports:
      - "8080:8080"
    command: -selenoidUri ...
```
See: https://stackoverflow.com/questions/37366857/how-to-pass-arguments-to-entrypoint-in-docker-compose-yml

Did it help?

**Comment by AleksanderPopov** [comment]
@vania-pooh thanks, i did't know about `command` instruction in docker compose! Yes, it works now, but to make this work i added link to selenoid container, so in `command` command for selenoid-ui we can replace IPAddress of selenoid by its name. That's the final version of yaml file for windows:

```
version: '2'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - ".:/etc/selenoid"
      - "//var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"

  selenoid-ui:
    links:
       - selenoid
    network_mode: bridge
    image: aerokube/selenoid-ui
    ports:
      - "8080:8080"
    command: -selenoid-uri http://selenoid:4444
```

Seems its a bit tricky to work with selenoid in windows, may be we need to add these steps into documentation, to make its easier for windows users use such nice tool as selenoid? :)
