### ISSUE TITLE
Running Selenoid in restricted docker environment

### ISSUE THREAD

**Issue by taraspos** [aerokube/selenoid#966]
Hello,
I'm trying to run the selenoid tests in the Bitbucket Pipelines, however, the [docker usage in there is quite restricted](https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/).

Firstly I faced a problem with the `privileged` mode.
`2020/08/06 14:26:32 [0] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed]`
Then, after adding the `-disable-privileged` I'm having a problem with the added capabilities.
`2020/08/06 14:29:31 [0] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: authorization denied by plugin pipelines: --cap-add is not allowed]`

Doing some research, I found that people are saying that it should be possible to run Chrome without `cap=SYS_ADMIN` or `privileged` mode while using `--no-sandbox`: https://github.com/Zenika/alpine-chrome#-with---no-sandbox

Can did you try such a setup? Would that work?
I checked the Selenoid code and looks like currently there is no way to run the container without `cap=SYS_ADMIN` or `privileged` mode. If that would work maybe that makes sense to add it? 

I guess this is related to #934 #251 

Thanks.

**Comment by vania-pooh** [comment]
@Trane9991 Selenoid has the following flag for that case:
```
-disable-privileged
    Whether to disable privileged container mode
```
This is described in docs: https://aerokube.com/selenoid/latest/#_selenoid_cli_flags

**Comment by Trane9991** [comment]
In the issue description I mentioned that I tried that flag.

**Comment by vania-pooh** [comment]
@Trane9991 currently using CAP_SYS_ADMIN is hard-coded.

**Comment by Trane9991** [comment]
I know, I've seen that in the code.
I could prepare PR to change that if you can confirm that it is possible to run the Selenoid browser images without that capability.

**Comment by vania-pooh** [comment]
@Trane9991 could you briefly describe what exactly would you like to change first?

**Comment by Trane9991** [comment]
So, for now, I managed to build a workaround that works for now with `selenoid -disable-docker` binary running in the headless chrome from [zenika/alpine-chrome](https://github.com/Zenika/alpine-chrome#-with---no-sandbox) docker image.

However, I have an idea of introducing `-restricted-docker-mode` flag for selenoid which will run containers following all Docker restrictions from Bitbucket Pipelines (and I think all other Docker-based CI systems), namely:
- Run without `privileged` mode
- Run without any added system capabilities
- Do host volume mounts as the subdirectories of the current directory only
- Add additional env variable as `SELENOID_FLAGS` to the Dockerfile, because bitbucket-pipelines does not allow to modify executed command for the service containers, only setting variables.

However, this is just an idea, that needs to be tested that it will "really" work, and since I managed to build a workaround I'm not going to work on this right now, maybe will pickup somewhere later.

Thanks, let me know what you think.

**Comment by Eleno4kaLap** [comment]
@Trane9991 , 
I have the same problem. Can you share your Bitbucket Pipelines, please? And one more question: did you try running tests in other browsers in Bitbucket Pipelines using selenoid?

**Comment by Trane9991** [comment]
@Eleno4kaLap I ended up running `docker-compose` in bitbucket-pipelines.

```yml
version: "3.8"
services:
  selenoid:
    image: zenika/alpine-chrome:86-with-selenoid
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
  tests:
    image: "gradle"
    command:
      - command
      - to
      - run
      - tests
    environment:
      - SELENOID_URL=http://selenoid:4444
    depends_on:
      - selenoid
```

then, in bitbucket pipelines the following step:
```yml
      name: Selenium Tests
      image: docker/compose
      script:
        - docker-compose up  --build --exit-code-from tests
      services:
        - docker
      caches:
        - docker
      artifacts:
        - video/**
        - screenshots/**
        - build/test-results/**
        - build/reports/**
   ```
